import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import wolf from "../images/download.jpeg"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <div className='flex flex-col text-center sm:flex-row'>
			<Image className="sm:rounded-full"src={wolf} />
      <h1>Adam Andrews</h1>
      <h2>I code</h2>
      </div>
		</div>
	);
}
