import Head from 'next/head';
import Image from 'next/image';
import wolf from "../images/download.jpeg"

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <div className={`flex flex-col text-center sm:flex-row sm:items-center sm:mx-auto
      ${false && "animate-pulse"}`}>
			<Image className="w-full sm:w-1/2 sm:rounded-full sm:max-w-sm" src={wolf} />
      <div className='mt-5 sm:ml-5'>
      <h1>Adam Andrews</h1>
      <h2>I code</h2>
      </div>
      </div>
		</div>
	);
}
