import Head from 'next/head';
import Image from 'next/image';
import Profile from '../components/Profile';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <Profile/>

      <div flex="flex gap-x-5">
      <button className='btn'>Create new todo</button>
      <button className='bg-blue-400'>Help</button>
      </div>

		</div>
	);
}
